Internal Server Error: /forum/
Traceback (most recent call last):
  File "C:\Users\mahdi\Desktop\programming\tahlil_proj\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\mahdi\Desktop\programming\tahlil_proj\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\mahdi\Desktop\programming\tahlil_proj\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\mahdi\Desktop\programming\tahlil_proj\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mahdi\Desktop\programming\tahlil_proj\venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\mahdi\Desktop\programming\tahlil_proj\venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\mahdi\Desktop\programming\tahlil_proj\venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\mahdi\Desktop\programming\tahlil_proj\venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\mahdi\Desktop\programming\tahlil_proj\config\forum\views.py", line 20, in get
    return paginator.get_paginated_response(serializer.data)
                                            ^^^^^^^^^^^^^^^
  File "C:\Users\mahdi\Desktop\programming\tahlil_proj\venv\Lib\site-packages\rest_framework\serializers.py", line 795, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "C:\Users\mahdi\Desktop\programming\tahlil_proj\venv\Lib\site-packages\rest_framework\serializers.py", line 249, in data
    self._data = self.to_representation(self.instance)
                 ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\mahdi\Desktop\programming\tahlil_proj\venv\Lib\site-packages\rest_framework\serializers.py", line 714, in to_representation
    self.child.to_representation(item) for item in iterable
                                                   ^^^^^^^^
TypeError: 'CustomPagination' object is not iterable
"GET /forum/ HTTP/1.1" 500 127470
Internal Server Error: /forum/
Traceback (most recent call last):
  File "C:\Users\mahdi\Desktop\programming\tahlil_proj\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\mahdi\Desktop\programming\tahlil_proj\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\mahdi\Desktop\programming\tahlil_proj\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\mahdi\Desktop\programming\tahlil_proj\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mahdi\Desktop\programming\tahlil_proj\venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\mahdi\Desktop\programming\tahlil_proj\venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\mahdi\Desktop\programming\tahlil_proj\venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\mahdi\Desktop\programming\tahlil_proj\venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\mahdi\Desktop\programming\tahlil_proj\config\forum\views.py", line 20, in get
    return paginator.get_paginated_response(serializer.data)
                                            ^^^^^^^^^^^^^^^
  File "C:\Users\mahdi\Desktop\programming\tahlil_proj\venv\Lib\site-packages\rest_framework\serializers.py", line 795, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "C:\Users\mahdi\Desktop\programming\tahlil_proj\venv\Lib\site-packages\rest_framework\serializers.py", line 249, in data
    self._data = self.to_representation(self.instance)
                 ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\mahdi\Desktop\programming\tahlil_proj\venv\Lib\site-packages\rest_framework\serializers.py", line 714, in to_representation
    self.child.to_representation(item) for item in iterable
                                                   ^^^^^^^^
TypeError: 'CustomPagination' object is not iterable
"GET /forum/ HTTP/1.1" 500 127469
Internal Server Error: /forum/
Traceback (most recent call last):
  File "C:\Users\mahdi\Desktop\programming\tahlil_proj\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\mahdi\Desktop\programming\tahlil_proj\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\mahdi\Desktop\programming\tahlil_proj\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\mahdi\Desktop\programming\tahlil_proj\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mahdi\Desktop\programming\tahlil_proj\venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\mahdi\Desktop\programming\tahlil_proj\venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\mahdi\Desktop\programming\tahlil_proj\venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\mahdi\Desktop\programming\tahlil_proj\venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\mahdi\Desktop\programming\tahlil_proj\config\forum\views.py", line 20, in get
    return paginator.get_paginated_response(serializer.data)
                                            ^^^^^^^^^^^^^^^
  File "C:\Users\mahdi\Desktop\programming\tahlil_proj\venv\Lib\site-packages\rest_framework\serializers.py", line 795, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "C:\Users\mahdi\Desktop\programming\tahlil_proj\venv\Lib\site-packages\rest_framework\serializers.py", line 249, in data
    self._data = self.to_representation(self.instance)
                 ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\mahdi\Desktop\programming\tahlil_proj\venv\Lib\site-packages\rest_framework\serializers.py", line 714, in to_representation
    self.child.to_representation(item) for item in iterable
                                                   ^^^^^^^^
TypeError: 'CustomPagination' object is not iterable
"GET /forum/ HTTP/1.1" 500 127469
Internal Server Error: /forum/
Traceback (most recent call last):
  File "C:\Users\mahdi\Desktop\programming\tahlil_proj\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\mahdi\Desktop\programming\tahlil_proj\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\mahdi\Desktop\programming\tahlil_proj\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\mahdi\Desktop\programming\tahlil_proj\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mahdi\Desktop\programming\tahlil_proj\venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\mahdi\Desktop\programming\tahlil_proj\venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\mahdi\Desktop\programming\tahlil_proj\venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\mahdi\Desktop\programming\tahlil_proj\venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\mahdi\Desktop\programming\tahlil_proj\config\forum\views.py", line 20, in get
    return paginator.get_paginated_response(serializer.data)
                                            ^^^^^^^^^^^^^^^
  File "C:\Users\mahdi\Desktop\programming\tahlil_proj\venv\Lib\site-packages\rest_framework\serializers.py", line 795, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "C:\Users\mahdi\Desktop\programming\tahlil_proj\venv\Lib\site-packages\rest_framework\serializers.py", line 249, in data
    self._data = self.to_representation(self.instance)
                 ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\mahdi\Desktop\programming\tahlil_proj\venv\Lib\site-packages\rest_framework\serializers.py", line 714, in to_representation
    self.child.to_representation(item) for item in iterable
                                                   ^^^^^^^^
TypeError: 'CustomPagination' object is not iterable
"GET /forum/ HTTP/1.1" 500 127470
Internal Server Error: /forum/
Traceback (most recent call last):
  File "C:\Users\mahdi\Desktop\programming\tahlil_proj\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\mahdi\Desktop\programming\tahlil_proj\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\mahdi\Desktop\programming\tahlil_proj\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\mahdi\Desktop\programming\tahlil_proj\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mahdi\Desktop\programming\tahlil_proj\venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\mahdi\Desktop\programming\tahlil_proj\venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\mahdi\Desktop\programming\tahlil_proj\venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\mahdi\Desktop\programming\tahlil_proj\venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\mahdi\Desktop\programming\tahlil_proj\config\forum\views.py", line 20, in get
    return paginator.get_paginated_response(serializer.data)
                                            ^^^^^^^^^^^^^^^
  File "C:\Users\mahdi\Desktop\programming\tahlil_proj\venv\Lib\site-packages\rest_framework\serializers.py", line 795, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "C:\Users\mahdi\Desktop\programming\tahlil_proj\venv\Lib\site-packages\rest_framework\serializers.py", line 249, in data
    self._data = self.to_representation(self.instance)
                 ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\mahdi\Desktop\programming\tahlil_proj\venv\Lib\site-packages\rest_framework\serializers.py", line 714, in to_representation
    self.child.to_representation(item) for item in iterable
                                                   ^^^^^^^^
TypeError: 'CustomPagination' object is not iterable
"GET /forum/ HTTP/1.1" 500 129695
